[package]
edition = "2024"
name = "mq-hir"
publish = false
version = "0.1.0"

[dependencies]
compact_str = {workspace = true}
itertools = {workspace = true}
mq-lang = {path = "../../crates/mq-lang", version = "0.1.0"}
rustc-hash = {workspace = true}
slotmap = {workspace = true}
strsim = "0.11.1"
thiserror = {workspace = true}
url = "2.5.4"

[dev-dependencies]
rstest = {workspace = true}
