[package]
authors = ["Takahiro Sato <harehare1110@gmail.com>"]
description = "mq is a Markdown processing tool that can filter markdown nodes by using jq-like syntax."
documentation = "https://github.com/harehare/mq/blob/master/docs/README.md"
edition = "2024"
exclude = [".github"]
homepage = "https://harehare.github.io/mq/"
keywords = ["markdown", "jq", "query"]
license-file = "LICENSE"
name = "mq-lang"
readme = "README.md"
repository = "https://github.com/harehare/mq"
version = "0.1.0"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.39"
compact_str = {workspace = true}
dirs = "6.0.0"
env_logger = "0.11.6"
itertools = {workspace = true}
log = "0.4.22"
miette = {workspace = true}
mq-md = {path = "../../crates/mq-md", version = "0.1.0"}
nom = {version = "7.1.3"}
nom_locate = "4.2.0"
percent-encoding = "2.3.1"
regex = "1.11.1"
rustc-hash = {workspace = true}
thiserror = {workspace = true}

[dev-dependencies]
criterion = "0.5.1"
rstest = {workspace = true}

[[bench]]
harness = false
name = "benchmark"
