version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

project_name: mq

builds:
  - builder: rust
    flags:
      - --release
      - --package=mq-cli
      - --bin=mq
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin

archives:
  - format: tar.gz
    name_template: >-
      {{.ProjectName}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: harehare
    name: mq
