[package]
authors = ["Takahiro Sato <harehare1110@gmail.com>"]
default-run = "mq"
description = "mq is a Markdown processing tool that can filter markdown nodes by using jq-like syntax."
documentation = "https://github.com/harehare/mq/blob/master/docs/README.md"
edition = "2024"
exclude = [
  ".github",
  "editors/*",
  "playground/*",
  ".goreleaser.yaml",
  "justfile",
  "tests",
  "examples",
  "docs",
  "Dockerfile",
]
homepage = "https://harehare.github.io/mq/"
keywords = ["markdown", "jq", "query"]
license-file = "LICENSE"
name = "mq-cli"
readme = "README.md"
repository = "https://github.com/harehare/mq"
version = "0.1.0"

[workspace]
members = ["crates/mq-lang", "crates/mq-repl", "crates/mq-md", "crates/mq-lsp", "crates/mq-hir", "crates/mq-formatter", "fuzz", "crates/mq-wasm"]

[dependencies]
clap = {version = "4.5.31", features = ["derive"]}
clap-verbosity-flag = "3.0.2"
clap_complete = "4.5.45"
colored = "2.2.0"
env_logger = "0.11.6"
itertools = "0.14.0"
log = "0.4.22"
miette = {version = "7.4.0", features = ["fancy"]}
mq-formatter = {path = "./crates/mq-formatter", version = "0.1.0"}
mq-lang = {path = "./crates/mq-lang", version = "0.1.0"}
mq-md = {path = "./crates/mq-md", version = "0.1.0"}
mq-repl = {path = "./crates/mq-repl", version = "0.1.0"}
syntect = {version = "5.2.0", default-features = false, features = ["default-fancy"]}

[dev-dependencies]
assert_cmd = "2.0.16"
rstest = "0.23.0"

[[bin]]
doc = false
name = "mq"
path = "src/main.rs"

[profile.release]
lto = "fat"
opt-level = 3
panic = 'abort'
strip = "symbols"
