[package]
edition = "2024"
name = "mdq-formatter"
version = "0.1.0"

[dependencies]
mdq-lang = {path = "../../crates/mdq-lang", version = "0.1.0"}
rustc-hash = {workspace = true}

[dev-dependencies]
rstest = {workspace = true}
