[package]
edition = "2024"
name = "mdq-lang-fuzz"
publish = false
version = "0.1.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = {version = "1.4.1", features = ["derive"]}
libfuzzer-sys = "0.4"
mdq-lang = {path = "../crates/mdq-lang", version = "0.1.0"}

[[bin]]
bench = false
doc = false
name = "interpreter"
path = "fuzz_targets/interpreter.rs"
test = false
