[package]
edition = "2024"
name = "mq-md"
publish = false
version = "0.1.0"

[dependencies]
compact_str = {workspace = true}
comrak = "0.33.0"
itertools = {workspace = true}
markdown = "1.0.0-alpha.21"
miette = {workspace = true}

[dev-dependencies]
rstest = "0.23.0"
