[package]
edition = "2024"
name = "mq-repl"
version = "0.1.0"

[dependencies]
arboard = "3.4.1"
colored = "3.0.0"
dirs = "6.0.0"
itertools = {workspace = true}
miette = {workspace = true}
mq-hir = {path = "../../crates/mq-hir", version = "0.1.0"}
mq-lang = {path = "../../crates/mq-lang", version = "0.1.0"}
mq-md = {path = "../../crates/mq-md", version = "0.1.0"}
rustyline = "15.0.0"
strum = {version = "0.26.3", features = ["derive"]}
