[book]
authors = ["harehare"]
language = "en"
multilingual = false
src = "src"
title = "mq - jq like tool for markdown processing"

[output.html]
git-repository-url = "https://github.com/harehare/mq"
site-url = "/mq/book"
